version: '3.0'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - EAGER_SERVICE_LOADING=1
      - SERVICES=sns,sqs
    ports:
      - '4566:4566'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  policy_db:
    image: "mcr.microsoft.com/mssql/server"
    hostname: "policy_db"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      SA_PASSWORD: "CE#!4Z4#Fjp2xKoE"
    ports:
      - "11433:1433"